### ISSUE TITLE
devspace How to change Deployment CMD?

### ISSUE THREAD

**Issue by D-wenhao** [loft-sh/devspace#1175]
**Is your feature request related to a problem?**  
> the following is my devspace.yaml:
```
deployments:
- name: "master"
  helm:
    chart:
      name: master
      version: 0.1.1
      repo: "https:/xxx/chartrepo/master"
    valuesFiles:
    - values.yaml
dev:
  open:
  - url: https://local-env.mastergo.com
  sync:
  - imageName: master
    localSubPath: ./
    containerPath: /app
  interactive:
    images:
    - name: master
    defaultEnabled: true
```

> I want to chage the deployment helm image ENTRYPOINT or CMD as sleep 100000，I try to add interactive in devspace.yaml but not good. How to do it?

**Which solution do you suggest?**  

**Which alternative solutions exist?**  

**Additional context**  

/kind feature
