### ISSUE TITLE
Timeout parameter not working with Helm v3

### ISSUE THREAD

**Issue by alexandrefilgueira** [loft-sh/devspace#1234]
**What happened?**  
When using the timeout parameter as you use to use it for helm v2 in the helm block for v3, it says:
`invalid argument "900" for "--timeout" flag: time: missing unit in duration "900"`
Because in helm v3 you should put it as 900s

If you try to use 900s instead, you get the error:
` cannot unmarshal !!str `900s` into int64`

**What did you expect to happen instead?**  
900s should work with helm v3

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Define a timeout and use helm v3 in your devspace.yaml

**Local Environment:**  
- DevSpace Version: 5.4.0-beta.0
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: minikube
- Kubernetes Version: v1.19.4

/kind bug

**Comment by FabianKramm** [comment]
@alexandrefilgueira thanks for reporting this issue! The `timeout` parameter is somewhat deprecated and we encourage users to use `upgradeArgs` instead:
```yaml
deployments:
- name: quickstart
  helm:
    componentChart: true
    upgradeArgs:
    - --timeout
    - 900s
    values:
      containers:
      - image: myusername/devspace
      service:
        ports:
        - port: 3000
```
