### ISSUE TITLE
Feature Request: use Secret and ConfigMap to environment variable of kaniko pod

### ISSUE THREAD

**Issue by sarub0b0** [loft-sh/devspace#1348]
**Is your feature request related to a problem?**  
Yes. I have my own npm and gem packages in private repositories, and I use them to build images and develop rails and react.
I don't want to store access tokens and passwords in the images at the time of the build images, and I set `--build-arg` for the
NPM_TOKEN and BUNDLE_GITHUB\_\_COM variables from Secret and ConfigMap.
To achieve this, I need to mount the build scripts and sensitive data to kaniko Pod, but this is complex and difficult to manage.

I don't also want to use this method if possible because team members share the devspace.yaml.
I want to use Secret and ConfigMap.

```yaml
# devspace.yaml
kaniko:
  env:
    NPM_TOKEN: ${NPM_TOKEN}
```

**Which solution do you suggest?**  
Adding new key like `valueFrom` to `kaniko.env`.
or adding new key to `kaniko.**`.

**Which alternative solutions exist?**

- Mount a ConfigMap that has the build script
- Mount a Secret that has access tokens
- Set kaniko image `gcr.io/kaniko-project/executor:debug`
- Add `images.app.build.kaniko.command`, and set build script
- Add `--build-arg=...` option to kaniko's args

Example:

```yaml
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-script
data:
  build.sh: |
    #!/bin/sh
    export TOKEN=$(cat <Mounted secret file>)
    /kaniko/executor "$@"
---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: access-token
data:
  TOKEN: ********************
```

```yaml
# devspace.yaml
image: gcr.io/kaniko-project/executor:debug
command:
  - /opt/bin/build.sh
args:
additionalMounts:
  - secret
    ...
  - configMap
    ...
```

**Additional context**

/kind feature
