### ISSUE TITLE
ability deploy and purge single deployment

### ISSUE THREAD

**Issue by leventogut** [loft-sh/devspace#1375]
**Is your feature request related to a problem?**  
yes, 

1) I have a config map that I change locally and need to redeploy bu tI don't have any tool to do that. I am forced to use purge

2) changing environment values requires a redeploy,

**Which solution do you suggest?**  
redeploy the deployment via uninstalling and installing via helm

**Which alternative solutions exist?**  

**Additional context**  

/kind feature

**Comment by leventogut** [comment]
tried following, seeing: app image rebuilds when just configmap is changed:
```
  autoReload:
    paths:
    - Dockerfile
    - deploy/configmap.yaml
    images:
    - app
```
