### ISSUE TITLE
Use `options` field for Kaniko from Docker (in fallback case)

### ISSUE THREAD

**Issue by saruman9** [loft-sh/devspace#1376]
**Is your feature request related to a problem?**  
Yes.
Options not inherited from `images.app.build.docker.options` when builder changed to Kaniko (as fallback for Docker).

**Which solution do you suggest?**  
Inherit options for Kaniko from Docker in fallback case.

**Which alternative solutions exist?**  
Copy `images.app.build.docker.options` to `images.app.build.kaniko.options`.

/kind feature

**Comment by FabianKramm** [comment]
@saruman9 thanks for creating this issue! They actually should get copied by default, could you provide a sample devspace.yaml where this is not the case?

**Comment by saruman9** [comment]
My fault: I don't test the case without the `kaniko` field.
Example of `devspace.yaml`, where Kaniko will not use `options` field from `docker`:
```yaml
version: v1beta9
images:
  default:
    image: default
    build:
      docker:
        options:
          target: base
          buildArgs:
            TEST: test
      kaniko:
        snapshotMode: redo
        args:
          - --use-new-run
```

It's normal, that Kaniko don't run with `base` target and `TEST` build arguments, because `images.default.kaniko.options` is empty. But in cases where Kaniko will works as fallback engine I want to use additional options (`snapshotMode`, `args` for example).
