### ISSUE TITLE
autoScaling.horizontal.maxReplicas dont generate any HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by pablorsk** [loft-sh/devspace#1398]
**What happened?**  

My deployment never auto-scale on DigitalOcean. Allways I have 1 replica. 

**What did you expect to happen instead?**  

I try with small values of memory or cpu, but never scale. Also, the only documentation about this feature is on legacy devspace.cloud site.

**How can we reproduce the bug?** 

My `devspace.yaml`

```yaml
deployments:
- name: app
  namespace: "mynamespace"
  helm:
    componentChart: true
    values:
      replicas: 1
      autoScaling:
        horizontal:
          maxReplicas: 3
          averageCPU: 5m
          # averageRelativeCPU: 1
      containers:
      - name: app
        image: pablorsk/app
```

**Local Environment:**  
- DevSpace Version: 5.10.0
- Operating System: linux 
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: DigitalOcean
- Kubernetes Version: v1.20.2

**Anything else we need to know?**  
![QJk58](https://user-images.githubusercontent.com/938894/114321672-57c19680-9af2-11eb-8d35-bc9fa12f31e4.png)
