### ISSUE TITLE
devspace now requires permission to get namespaces within k8s cluster

### ISSUE THREAD

**Issue by aanisimov** [loft-sh/devspace#1401]
**What happened?**  

devspace now requires permission to get namespaces within k8s cluster

`[info]   Using namespace 'copper'
[info]   Using kube context 'xxx'
[fatal]  Unable to create namespace: get namespace: namespaces "copper" is forbidden: User "system:serviceaccount:copper:copper-sa" cannot get resource "namespaces" in API group "" in the namespace "copper"`

**What did you expect to happen instead?**  

I expect older behavior - try to switch to namespace - without getting list of all available namespaces.

Or do have an argument that will skip getting/creating namespaces.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Run devspace dev with namespace stated when service account user that is used for devspace doesn't have permissions to get list of namespaces.

**Local Environment:**  
- DevSpace Version: 5.11.0
- Operating System: linux
- Deployment method: docker container

**Kubernetes Cluster:**  
- Cloud Provider: local

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@aanisimov thanks for creating this issue! Do you have an example `devspace.yaml` configuration with which we can reproduce this? Did you run `devspace dev` or another command?

**Comment by aanisimov** [comment]
devspace.yaml
```
version: v1beta8
dev:
  sync:
    - labelSelector:
        app: logic
      localSubPath: /project
      containerPath: /home/logic/logic
      disableDownload: true
      waitInitialSync: true
```
I'm running 
`devspace dev --verbose-sync`
