### ISSUE TITLE
cannot unmarshal !!str error when port-forwarding ports provided by environment variables

### ISSUE THREAD

**Issue by zadigus** [loft-sh/devspace#1431]
**What happened?**  

I am using a configuration that contains the following lines:
```yaml
version: v1beta7
vars:
- name: MY_SERVICE_PORT
  source: env
  default: 4000
[...]
dev:
   ports:
   - imageName: my-service
     forward:
     - port: ${MY_SERVICE_PORT}
       remotePort: 80
```
When I try to deploy any of my profiles, I get the error
```
cannot unmarshal !!str `4000` into int
```
If I comment out the `dev` section of my `devspace.yaml`, then the deployment is successful. Under Windows 10, on git bash, it works perfectly. Under Linux (especially alpine), I get the above error.

**What did you expect to happen instead?**  

I would expect to have no error. It used to work properly on both Linux and Windows.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Take the above simple snippet, just add an image to build and a deployment.

**Local Environment:**  
- DevSpace Version: 5.11.0
- Operating System: linux
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider:  other
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"archive", BuildDate:"2021-04-01T13:29:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"archive", BuildDate:"2021-04-01T13:25:36Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug
