### ISSUE TITLE
Use custom variables based on profile when running a devspace command

### ISSUE THREAD

**Issue by uncvrd** [loft-sh/devspace#1477]
Hi! Thanks for this incredible project, it has made my workflow so much easier. Just have a quick request. I'd love to be able to dynamically change the `profile` of `devspace` so that I can use `profile` defined `vars` within a `command`.

For example, I've defined a custom `command` that should change my `profile` to staging, and then use the `staging` `vars` within the `command`:

Here's my command, as you can see in the second item, I use the `devspace use profile staging` command to switch to my `staging` profile and then I have a custom `configure-project.sh` script to run some, well, configurations:

```
commands:
  - name: dev
    description: 'Runs kubernetes cluster locally'
    command: 'devspace use profile --reset
              && ./configure-project.sh 
                -a ${GOOGLE_SERVICE_ACCOUNT} 
  - name: deploy:staging
    description: 'Deploys to remote staging environment'
    command: 'devspace use profile staging
              && ./configure-project.sh 
                -a ${GOOGLE_SERVICE_ACCOUNT} 
```

Underneath my `commands`, I have a `vars` section defined`:

```
vars:
  - name: GOOGLE_SERVICE_ACCOUNT
    value: my_development_account@gcloud.com
```

Further below, I defined a `staging` profile:

```
profiles:
    - name: staging
    strategicMerge:
      vars:
        - name: GOOGLE_SERVICE_ACCOUNT
          value: my_staging_account@gcloud.com
```

The issue I've found is that when I run `devspace run deploy:staging` and I echo the `-a` (GOOGLE_SERVICE_ACCOUNT) flag within the script, the variable has not changed to my staging service account email. This does work if I run the command again...so I thought it might have to do with it taking a bit of time to switch profiles so I tried adding a `sleep` inbetween

```
    command: 'devspace use profile staging
              && sleep 5
              && ./configure-project.sh 
                -a ${GOOGLE_SERVICE_ACCOUNT} 
```

But that didn't work either. My guess is that the entire process needs to complete before the profile variables are updated? (But isn't that what the && should wait for...?) So I guess it just has to do with when the variables are actually "read"

**Is your feature request related to a problem?**  
I don't think so

**Which solution do you suggest?**  
Problem and solution described above

/kind feature

**Comment by FabianKramm** [comment]
@uncvrd thanks for creating this issue! The problem is that DevSpace will resolve the variables before actually executing the command, so a command
```
devspace use profile staging
              && ./configure-project.sh 
                -a ${GOOGLE_SERVICE_ACCOUNT} 
```
will be translated into 
```
devspace use profile staging
              && ./configure-project.sh 
                -a my_development_account@gcloud.com
```
before executing. 

What you can do is to use a little workaround which accomplishes your goal:
```yaml
version: v1beta10
vars:
  - name: GOOGLE_SERVICE_ACCOUNT
    value: my_development_account@gcloud.com
commands:
  - name: configure-project
    command: './configure-project.sh -a ${GOOGLE_SERVICE_ACCOUNT} '
  - name: dev
    command: 'devspace run configure-project'
  - name: deploy:staging
    command: 'devspace -p staging run configure-project'
profiles:
  - name: staging
    strategicMerge:
      vars:
      - name: GOOGLE_SERVICE_ACCOUNT
        value: my_staging_account@gcloud.com
```
