### ISSUE TITLE
Bug: Devspace replace pods with multiple label selectors alone fails with not unique error 

### ISSUE THREAD

**Issue by srinidhis05** [loft-sh/devspace#1499]
**What happened?**  
The devspace replacepods throwing Error in config: image selector or label selector is not unique in replace pods at index 0 when using labelselectors and the label selectors are unique 
 devspace.yaml 

```
version: v1beta10
dev:
  replacePods:
    - labelSelector:
        app: label1
      replaceImage: image2
      namespace: namespace
    - labelSelector:
        app: label2
      replaceImage: image2
      namespace: namespace
```

**What did you expect to happen instead?**  
The replace pods to work 

**How can we reproduce the bug?** (as minimally and precisely as possible)  
By adding a devspace yaml file with multiple replace pods options using label selector

**Local Environment:**  
- DevSpace Version: 5.14.3
- Operating System: mac
- Deployment method: apply

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.16.5

**Anything else we need to know?**  
The replace pods with multiple options only works with imageselector and the problem lies in the validation logic 

/kind bug
