### ISSUE TITLE
localSubPath is ignored by devspace sync

### ISSUE THREAD

**Issue by evyros** [loft-sh/devspace#1501]
[#933](https://github.com/loft-sh/devspace/issues/933) exists on 5.14.3 on my Apple Silicone, Big Sur 11.4.
It doesn't matter what value I give to `localSubPath` it's just being ignored.
```
version: v1beta10
images:
  api:
    image: org/api
deployments:
- name: rc
  helm:
    chart:
      name: ./k8s
    valuesFiles:
    - values.dev.yaml
dev:
  sync:
  - imageName: api
    labelSelector:
      tier: api
    containerName: api
    localSubPath: ./services/api
    excludePaths:
    - .git/
```
It is always using my current directory (project root, next to `devspace.yaml`).
Therefore I get this error:
```
[fatal]  error during shouldRebuild check: Dockerfile ./Dockerfile missing: stat ./Dockerfile: no such file or directory
```

**Local Environment:**
Operating System: Mac
Deployment method: helm
HELM version: 3.6.3
devspace version 5.14.3

**Kubernetes Cluster:**
Cloud Provider: local with docker for mac

**Comment by FabianKramm** [comment]
@evyros thanks for creating this issue! The problem is that the error happens during the build phase and you need to specify your dockerfile path, for example like this:
```yaml
version: v1beta10
images:
  api:
    image: org/api
    dockerfile: ./services/api/Dockerfile
    context: ./services/api
deployments:
- name: rc
  helm:
    chart:
      name: ./k8s
    valuesFiles:
    - values.dev.yaml
dev:
  sync:
  - imageName: api
    labelSelector:
      tier: api
    containerName: api
    localSubPath: ./services/api
    excludePaths:
    - .git/
```
