### ISSUE TITLE
Name attributes on dev.sync and dev.port configurations

### ISSUE THREAD

**Issue by noizwaves** [loft-sh/devspace#1577]
**Is your feature request related to a problem?**  

Yes. Currently, when using profile patch paths to specify a `dev.sync` or `dev.ports` item to remove, only fragile array indexes can be used. Because there is no "root level" property on these items, robust property selectors cannot be used.

Example (with array indexes):
```
...
dev:
  ports:
  - labelSelector:
      service: web
    forward:
      - port: 3000
        remotePort: 3000
  sync:
    - labelSelector:
        service: web
      excludePaths: []
profiles:
  - name: disable-web
    patches:
      - op: remove
        path: dev.ports[0]
      - op: remove
        path: dev.ports[0]
```

**Which solution do you suggest?**
Adding a new property, like `name` to the `dev.sync` and `dev.ports` configuration. This would allow the above example to be expressed in a robust way:
```
...
dev:
  ports:
  - name: web
    labelSelector:
      service: web
    forward:
      - port: 3000
        remotePort: 3000
  sync:
    - name: web
      labelSelector:
        service: web
      excludePaths: []
profiles:
  - name: disable-web
    patches:
      - op: remove
        path: dev.ports.name=web
      - op: remove
        path: dev.ports.name=web

```

**Which alternative solutions exist?**  
N/A

**Additional context**  
We are using profiles more heavily to control dynamic configuration in our cloud development environments. The ability to safely and reliably combine multiple profiles will be important for us.
