### ISSUE TITLE
Support for OCI Helm registries

### ISSUE THREAD

**Issue by antonlisovenko** [loft-sh/devspace#1640]
Hi

Thanks for this amazing tool.
Helm OCI registries is a new fashion now, most of container registries (ECR, Quay) support this format so it's quite convenient to publish the internal company Helm charts there and avoid the need to create a new Helm repository.

The way it's implemented in Helmsman for example is using the format `oci://my-registry.local/my-chart` (https://github.com/Praqma/helmsman/blob/master/docs/how_to/helm_repos/oci.md)

Are there plans to support OCI Helm in Devspace?

thank you
/kind feature

**Comment by FabianKramm** [comment]
@antonlisovenko thanks for creating this issue! Since this is just the chart name, did you try to use something like:
```yaml
deployments:
- name: test
  helm:
    chart:
      name: oci://my-registry.local/my-chart
```
As this would be translated to `helm install oci://my-registry.local/my-chart`, which might already work?
