### ISSUE TITLE
PersistentVolumeClaim "FailedScheduling" and "Waiting for containers to start..." 

### ISSUE THREAD

**Issue by cheslijones** [loft-sh/devspace#1702]
**What happened?**  
I added a Persistent Volume per [the documentation](https://devspace.sh/component-chart/docs/guides/persistent-volumes), but when I run `devspace dev` it sits on the following indefinitely:  
```
[wait] ⠙ Port-Forwarding: Waiting for containers to start... (293s)
```

**What did you expect to happen instead?**  
I was expecting it to create the PV/PVC and for the database to launch. The `devspace render` pretty closely resembles the manifests I used to use with `minikube` and `skaffold`, so I'm not sure 100% that it is a configuration issue.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
You can try to run a `devspace run` with the following configurations:
```
# Dockerfile
FROM postgres:13-alpine
EXPOSE 5432
# COPY *.sql /docker-entrypoint-initdb.d/
```
```
# devspace.yaml
version: v1beta11

vars:
- name: APP-NAME
  question: "Enter the app name:"
- name: DB
  value: postgres
- name: DB_NAME
  question: "Enter the database name:"
- name: DB_PASSWORD
  question: "Enter the database password:"
  password: true
- name: DB_USER
  question: "Enter the database user name:"

images:
  postgres:
    image: ${APP-NAME}/${DB}
    dockerfile: ${DB}/Dockerfile
    context: ${DB}/

deployments:
- name: ${DB}
  helm:
    componentChart: true
    values:
      containers:
      - image: ${APP-NAME}/${DB}
        env:
        - name: POSTGRES_DB
          value: ${DB_NAME}
        - name: POSTGRES_USER
          value: ${DB_USER}
        - name: POSTGRES_PASSWORD
          value: ${DB_PASSWORD}
        - name: PGDATA
          value: /var/postgresql/data
        volumeMounts:
        - containerPath: /var/postgresql
          volume:
            name: ${DB}-data
            readOnly: false
      service:
        ports:
          - port: 5432
      volumes:
      - name: ${DB}-data
        size: "10Gi"
        accessModes: [ReadWriteMany]
dev:
  - name: ${DB}
    imageSelector: ${APP-NAME}/${DB}
    forward:
    - port: 5432
      remotePort: 5432
```

**Local Environment:**  
- DevSpace Version: `devspace version 5.16.0`
- Operating System: mac
- Deployment method: `helm`

**Kubernetes Cluster:**  
- Cloud Provider: `docker-desktop`
- Kubernetes Version: `1.21.4`

**Anything else we need to know?**  
There is no `kubectll log postgres-0` output.
 
The `kubectl describe pod postgres-0` shows the followingL
```
$ kubectl describe pod postgres-0  
Name:           postgres-0
Namespace:      k8s-demo
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=postgres
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=devspace-app
                controller-revision-hash=postgres-6dd4fc78f8
                statefulset.kubernetes.io/pod-name=postgres-0
Annotations:    helm.sh/chart: component-chart-0.8.2
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/postgres
Containers:
  container-0:
    Image:     app/postgres:NSskmgT
    Port:       <none>
    Host Port:  <none>
    Environment:
      POSTGRES_DB:        postgres_db
      POSTGRES_USER:      postgres_user
      POSTGRES_PASSWORD:  postgres_password
      PGDATA:             /var/postgresql/data
    Mounts:
      /var/postgresql from postgres-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8trhb (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  postgres-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  postgres-data-postgres-0
    ReadOnly:   false
  kube-api-access-8trhb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m19s  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  2m18s  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
```

/kind bug
