### ISSUE TITLE
Background hooks in plugins don't seem to work

### ISSUE THREAD

**Issue by ninjaprox** [loft-sh/devspace#1714]
**What happened?**  

It seems that DevSpace doesn't execute background hooks in plugins.

**What did you expect to happen instead?**  

DevSpace should execute both non-background and background hooks in plugins.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Here's the simple plugin to test out:

```yaml
# plugin.yaml

version: 0.0.1
name: test-devspace-plugin
hooks:
  - event: devCommand:before:sync
    baseArgs:
    - before-sync
  - event: devCommand:after:sync
    baseArgs:
    - after-sync
    background: true
binaries:
  - os: darwin
    arch: amd64
    path: ./plugin.sh
```

```bash
#!/bin/bash

echo "A DevSpace plugin"
echo "$@"
```

```
devspace dev

[info]   Using namespace '<redacted>'
[info]   Using kube context '<redacted>'

#########################################################
[info]   DevSpace UI available at: http://localhost:8090
#########################################################

[done] √ Reverse port forwarding started at 4864:4864 (<redacted>)
A DevSpace plugin
before-sync
[0:sync] Waiting for pods...
[0:sync] Starting sync...
[0:sync] Start syncing
[0:sync] Sync started on <redacted>/src <-> /app/src (Pod: <redacted>)
[0:sync] Waiting for initial sync to complete
[0:sync] Helper - Use inotify as watching method in container
[0:sync] Downstream - Initial sync completed
[0:sync] Upstream - Initial sync completed
[info]   Starting log streaming
```

**Local Environment:**  
- DevSpace Version: devspace version 5.16.0

- Operating System: mac
- Deployment method: kubectl apply

**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug
