### ISSUE TITLE
config expressions ... working?

### ISSUE THREAD

**Issue by shaunc** [loft-sh/devspace#1716]
**What happened?**  

I wanted to try the new config expressions to break up a very long devspace.yaml file. Accordingly, I copied variables (the first section at the top) into a separate file, and then replaced the section with

```yaml
vars: $(cat devspace/devspace.yaml)
```

**What did you expect to happen instead?**  

I expected the configuration to continue to work.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Typing devspace print, I get:
```shell
[fatal]  parse variables: Error loading config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `$(cat d...` into []*latest.Variable
```

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 5.16.2
- Operating System: mac
- Deployment method: na

**Kubernetes Cluster:**  na?

**Anything else we need to know?**  

### devspace/devspace-vars.yaml:
```yaml
  - name: LETSENCRYPT_STAGE
    question: "Use letsencrypt staging (=dev) or production (=prod) issuer?"
    options:
    - dev
    - prod
  - name: GITHUB_KEY_PATH
    question: "Path to github private repo key for build"
```

I tried various variations: unindented; tried "cat" on next line, or after "-" ...

### Other

The other sections seem working, with the exception of "proflile" which also causes a similar issue:
```yaml
[fatal]  error parsing profile at profiles[0]: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `$(cat d...` into latest.ProfileConfig
```

/kind bug
