### ISSUE TITLE
Which directory are exclude paths relative to?

### ISSUE THREAD

**Issue by kickthemooon** [loft-sh/devspace#1726]
I am syncing like:
```
dev:
  sync:
    - labelSelector:
        app: my-app
      containerName: my-container
      namespace: my-namespace
      containerPath: /app
      initialSync: mirrorLocal
      uploadExcludeFile: ./path/to/upload-exclude-paths.gitignore
      downloadExcludeFile: ./path/to/download-exclude-paths.gitignore
```

/app folder structure looks like:
```
- foo
- bar
    - foo
```

If I have an upload exclude path like:
```
/foo
```

I expect only the the top level `foo` not to be synced and `bar/foo/` continue being synced

Thats not what is happening.
What happens is, both foo directories don't sync.

Am I missing something?
What are the exclude paths, both download and upload, relative to?
How to exclude only top level directories, relative to devspace.yaml or, if present, localSubPath from uploading?
