### ISSUE TITLE
Cannot specify Helm timeout 

### ISSUE THREAD

**Issue by antonlisovenko** [loft-sh/devspace#1727]
I have configured timeout in Helm:

```
  - name: postgres
    helm:
      chart:
        repo: https://charts.bitnami.com/bitnami
        name: postgresql
      wait: true
      timeout: 30s
```

According to the [Helm docs](https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback) this must be a `time.duration` value (30s, 2m etc)
But I get the parsing error from Devspace:

```
[fatal]  convert config: Error loading config: yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `30s` into int64

```

**Local Environment:**  
- DevSpace Version: devspace version 5.16.2
- Operating System: mac
- Deployment method: helm

/kind bug
