### ISSUE TITLE
SIGSEGV on replacing by empty value

### ISSUE THREAD

**Issue by emoreth** [loft-sh/devspace#1774]
**What happened?**  

```
[my-pod] Replacing Pod username/my-pod-5f79f5894c-94zg7...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x524996d]

goroutine 116 [running]:
github.com/loft-sh/devspace/pkg/devspace/config/loader/patch.replaceChildAtIndex(0xc00117b400, 0xc001223fb0, 0x0)
	github.com/loft-sh/devspace/pkg/devspace/config/loader/patch/operation.go:156 +0x8d
github.com/loft-sh/devspace/pkg/devspace/config/loader/patch.(*Operation).replace(...)
	github.com/loft-sh/devspace/pkg/devspace/config/loader/patch/operation.go:96
github.com/loft-sh/devspace/pkg/devspace/config/loader/patch.(*Operation).Perform(0xc000629980, 0x3c35)
	github.com/loft-sh/devspace/pkg/devspace/config/loader/patch/operation.go:64 +0x51c
github.com/loft-sh/devspace/pkg/devspace/config/loader/patch.Patch.Apply({0xc00051e000, 0x7, 0x4000}, {0xc000640000, 0xc0011c63c0, 0x4000})
	github.com/loft-sh/devspace/pkg/devspace/config/loader/patch/patch.go:20 +0x1c5
github.com/loft-sh/devspace/pkg/devspace/config/loader.ApplyPatchesOnObject(0x5d07dc8, {0xc001d18d80, 0xb, 0x27})
	github.com/loft-sh/devspace/pkg/devspace/config/loader/profile.go:187 +0x4c7
github.com/loft-sh/devspace/pkg/devspace/services/podreplace.applyPodPatches(0xc001766918, 0xc001d0c1b0)
	github.com/loft-sh/devspace/pkg/devspace/services/podreplace/replace.go:557 +0x94
github.com/loft-sh/devspace/pkg/devspace/services/podreplace.replace({0x5d20bf8, 0xc0001a4008}, {0x5d6de08, 0xc001840fc0}, 0xc0019a0360, {0x5d07120, 0xc000338000}, {0x5d3cff8, 0xc001da84b0}, {0x0, ...}, ...)
	github.com/loft-sh/devspace/pkg/devspace/services/podreplace/replace.go:341 +0x225
github.com/loft-sh/devspace/pkg/devspace/services/podreplace.(*replacer).ReplacePod(0xc0010836c8, {0x5d20bf8, 0xc0001a4008}, {0x5d6de08, 0xc001840fc0}, {0x5d3cff8, 0xc001da84b0}, {0x0, 0x0, 0x0}, ...)
	github.com/loft-sh/devspace/pkg/devspace/services/podreplace/replace.go:106 +0x83d
github.com/loft-sh/devspace/pkg/devspace/services.(*client).newReplacePodsFn.func1()
	github.com/loft-sh/devspace/pkg/devspace/services/pod_replace.go:29 +0x270
github.com/loft-sh/devspace/pkg/devspace/services.(*runner).Run.func1()
	github.com/loft-sh/devspace/pkg/devspace/services/runner.go:37 +0x75
created by github.com/loft-sh/devspace/pkg/devspace/services.(*runner).Run
	github.com/loft-sh/devspace/pkg/devspace/services/runner.go:34 +0x9d
```

**What did you expect to happen instead?**  

```
[my-pod] Replacing Pod username/my-pod-5f79f5894c-94zg7...
[my-pod] Scaled down Deployment username/my-pod
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  

I used to have:
```
profiles:
    -   name: __base
        patches:
          - op: add
            path: dev.replacePods[0].patches
            value:
                op: replace
                path: spec.initContainers
```
And it worked well to replace initContainers that don't need to run on veery restart.

Now it only works if I explicitly add `[]` as a value:

```
profiles:
    -   name: __base
        patches:
          - op: add
            path: dev.replacePods[0].patches
            value:
                op: replace
                path: spec.initContainers
                value: []
```

**Local Environment:**  
- DevSpace Version: 5.17.0
- Operating System: mac
- Deployment method: apply

**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: 1.18.12

**Anything else we need to know?**  

/kind bug
