### ISSUE TITLE
Expressions are not working on a map when using component charts in 5.18.0

### ISSUE THREAD

**Issue by dhruvbaldawa** [loft-sh/devspace#1816]
**What happened?**  
Expressions have stopped working on maps in component chart values after upgrading to 5.18.0. If I downgrade to 5.17.0, they are working as expected. 

The `populate-env` command over here reads a `.env` file and converts it into the map that devspace expects.

```yaml
deployment:
  - name: api
    helm:
      componentChart: true
      values:
        containers:
          - image: legacy-api
            env: $(populate-env ${API_DIR}/local.env)
        service:
          ports:
            - port: 9000
```

I see this error
```
[fatal]  deployments[1].helm.componentChart: component values are incorrect: yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `$(popula...` into []map[interface {}]interface {}
```

**What did you expect to happen instead?**  
`devspace print` command should work and not throw a YAML unmarshalling error. I expect the environment variables to be populated as expected

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Add an expression on the `env` for component chart on devspace 5.18.0, and run `devspace print` see if it succeeds.
```
env: '$(echo [{"name": "ENV", "value": "foo"}])'
```

**Anything else we need to know?**  

/kind bug
