### ISSUE TITLE
Component chart values are not evaluated as expressions

### ISSUE THREAD

**Issue by dhruvbaldawa** [loft-sh/devspace#1829]
Thanks for the fast turnaround time on #1816. This issue is an extension of the same issue

**What happened?**  
```yaml
deployment:
  - name: api
    helm:
      componentChart: true
      values:
        containers:
          - image: legacy-api
            env: $(populate-env ${API_DIR}/local.env)
        service:
          ports:
            - port: 9000
```

If I do `devspace print`, this is the output that I receive
```yaml
deployment:
  - name: api
    helm:
      componentChart: true
      values:
        containers:
          - image: legacy-api
            env: $(populate-env ${API_DIR}/local.env)
        service:
          ports:
            - port: 9000
```

I tried `devspace deploy` but it threw another error 
```
[fatal]  error deploying: error deploying api: Unable to deploy helm chart: error during 'helm upgrade ....': Error: UPGRADE FAILED: cannot patch "api" with kind Deployment: The order in patch list:
[map[name:FOO value:bar] map[name:ENV value:value]]
 doesn't match $setElementOrder list:
[map[name:FOO] map[name:ENV]]
```

**What did you expect to happen instead?**  
The output I expect is:
```yaml
deployment:
  - name: api
    helm:
      componentChart: true
      values:
        containers:
          - image: legacy-api
            env:
             - name: FOO
               value: bar
            - name: ENV
              value: value
        service:
          ports:
            - port: 9000
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Add an expression on the `env` for component chart on devspace 5.18.0, and run `devspace print`
```yaml
env: '$(echo [{"name": "ENV", "value": "foo"}, "name": "NAMESPACE", "value": "${DEVSPACE_NAMESPACE}"}])'
```
The output for `devspace print` should look like
```yaml
env:
    - name: ENV
      value: foo
    - name: NAMESPACE
      value: mynamespace
```

**Local Environment:**  
- DevSpace Version: 5.18.1
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: k3s
- Kubernetes Version: 1.23.0

/kind bug
