### ISSUE TITLE
Breaking change to profile operation `path` introduced in v5.18.0

### ISSUE THREAD

**Issue by erikkrieg** [loft-sh/devspace#1835]
**What happened?**  

We had a developer upgrade from devspace v5.17.0 to v.5.18.1 and when they attempted to run their project with `devspace dev` they hit the following error:

```sh
$ devspace dev
[info]   Using namespace '<REDACTED>'
[info]   Using kube context '<REDACTED>'
[fatal]  error validating profiles[0]: patches[7] path cannot be a variable
```

This error corresponded with something like this:

```yaml
profiles:
- name: demo
  patches:
  # Leaving out the 7 preceding items in this list
  - op: remove
    path: deployments.name=${PREFIX}server.helm.values.entrypoint
```

**What did you expect to happen instead?**  
Expected that with a minor version change that our devspace.yaml config would continue to pass the validation step and `devspace` commands would execute successfully.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Our file is not sharable without heavy modification. If more clarity is needed, I can take some time on request to provide and test out something to share.

**Local Environment:**  
- DevSpace Version: 5.18.1
- Operating System: mac

**Kubernetes Cluster:**  
- Cloud Provider:  aws

**Anything else we need to know?**  

Thanks for your help, and thanks for providing an excellent tool :D

/kind bug
