### ISSUE TITLE
DevSpace prompts user for var provided by plugin

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [loft-sh/devspace#1857]
**What happened?**  
DevSpace prompts the user for a variable that is provided by a plugin. After the user enters a value, it is ignored and the value provided by the plugin is used instead.

```
? Please enter a value for OPEN_COMMAND (<nil>) 
```

This only happens when the variable in question is missing from `generated.yaml`, so typically this happens only once.

**What did you expect to happen instead?**  
DevSpace does not prompt the user for a variable provided by a plugin.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Create a plugin that outputs a value in stdout.

```
vars:
  - name: OPEN_COMMAND
    baseArgs:
      - get_open
```

And of course, add it with `devspace add plugin ...`

My devspace.yaml:
```
version: v1beta11
...

commands:
  - name: open_url
    command: "${OPEN_COMMAND} 'https:...some url"
```

**Local Environment:**  
- DevSpace Version: 5.18.1
- Operating System: mac
- ARCH of the OS: AMD64

/kind bug
