### ISSUE TITLE
add volumeMounts through patches in dev replacePods

### ISSUE THREAD

**Issue by johnnypea** [loft-sh/devspace#1871]
Could you please point out what am I doing wrong?

Error:
```
[fatal]  replace pod: create copied pod: ReplicaSet.apps "app-0" is invalid: [spec.template.spec.containers[0].volumeMounts[2].name: Required value, spec.template.spec.containers[0].volumeMounts[2].name: Not found: "", spec.template.spec.containers[0].volumeMounts[2].mountPath: Required value]
```

My config
```
version: v1beta11

images:
  caddy:
    image: caddy
    dockerfile: Dockerfile
    context: .

  php:
    image: php
    dockerfile: Dockerfile
    context: .

- name: app
  helm:
    componentChart: true
    values:
      containers:
      - name: php-container
        image: php
        volumeMounts:
        - containerPath: /var/run/php
          volume:
            name: php-socket
            readOnly: false
      - name: caddy-container
        image: caddy
        volumeMounts:
        - containerPath: /var/run/php
          volume:
            name: php-socket
            readOnly: true
      service:
        ports:
        - containerPort: 80
          port: 8080
          protocol: TCP
        - containerPort: 443
          port: 4443
          protocol: TCP
        - containerPort: 443
          port: 4443
          protocol: UDP
      volumes:
      - name: php-socket
        size: 5Gi
      - name: php-public
        size: 5Gi

dev:
  replacePods:
    - imageSelector: php
      patches:
        - op: add
          path: spec.containers[0].volumeMounts
          value:
            containerPath: /srv/app/public
            volume:
              name: php-public
              readOnly: false 
  ports:
  - labelSelector:
      app.kubernetes.io/component: app
    forward:
    - port: 8080
    - port: 4443
```
