### ISSUE TITLE
Using devspace on multiple microservices

### ISSUE THREAD

**Issue by or-adar** [loft-sh/devspace#1879]
Hi,
I've heard about devspace not too long ago and couldn't find any answers to some questions I had on the available docs and would love to hear your opinion or see some examples.

I think that this tool could help a lot with my team's current develoment setup but I'm trying to figure out what would be a best practice for setting up our development environment using devspace.

Every microservice of ours has it's own git repo (aka polyrepo), so should I add a devspace.yml to each and every service and than create an additional git repo with devspace.yml that would have a `dependencies` section with references to the git repositories of my services?
Will it work when running `devspace dev`? if I'm working on a given service and my current branch isn't master, will devspace attemp to pull from my currently used branch or should I always set manually the `source.branch` option on development mode?
I'm talking about the following setup:
```
project-1               project-2               project-3               project-n
----------              ----------              ----------              ----------
.                       .                       .                       .
├── ...                 ├── ...                 ├── ...                 ├── ...
└── devspace.yml        └── devspace.yml        └── devspace.yml        └── devspace.yml

```
and then I'll create a new git repo which includes a devspace.yml with a dependencies section like so:
```yaml
dependencies:
- name: project-1 
  source:
    git: https://github.com/project-1
- name: project-2 
  source:
    git: https://github.com/project-2
- name: project-3
  source:
    git: https://github.com/project-3

  ...

- name: project-n
  source:
    git: https://github.com/project-n
```
so when I'll attempt to develop on one service or more I'll clone that repo with the dependencies yaml and run `devspace dev` from there,
then I could interact with the cloned dependencies as I please?
Will it also be able to hot reload changes on a dependency in the suggested structure above? (as I assume I'll have to run `devspace dev` from the root directory of the yaml file with all the listed dependncies, am I right?)

Also what is a best practice for defining the same dependency for multiple services?
For instance, let's say, I have 10 services that depend on the same postgres database, should I define it as a dependency on every devspace.yml that would require it or at the top of my `dependencies` section with the rest of my services?

If you have any examples I could see or any suggestion, I would love to see or hear those!

/kind question
