### ISSUE TITLE
Dependency cloning results in a cryptic error if it fails

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [loft-sh/devspace#2059]
**What happened?**
When a user is not properly authenticated to clone a dependency git repository, the clone silently fails and then the user is presented with `.devspace/dependencies/79dde... very long hex string .../devspace.yaml: no such file or directory`

**What did you expect to happen instead?**
The user sees the error from git or at least a helpful error message. Likewise, once this happens, things stay in a broken state until you reset dependencies, even if you fix the underlying issue.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Try cloning a private repo without logging in, or try `https` protocol when you have only `git` protocol set up, or vice versa.

My devspace.yaml:

```
    parents:
      - profile: myprofile
        source: 
          git: https://github.com/...some..path
          branch: main
```

**Local Environment:**

* DevSpace Version: 5.18.4
* Operating System: mac
* ARCH of the OS: AMD64 / ARM64

/kind bug
