### ISSUE TITLE
Variable override in command not working

### ISSUE THREAD

**Issue by markphillips100** [loft-sh/devspace#2060]
**What happened?**  
Upgraded from v6.0.0-alpha.7 to v6.0.0-alpha.16 and variable override in run command no longer applied.

**What did you expect to happen instead?**  
Specified variable should be used in called command.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Install v6.0.0-alpha.7
2. Run `devspace run cmd1`
    Output should be "some value".
3. Run `devspace run cmd2`
    Output should be "A different value".
4. Install v6.0.0-alpha.16
5. Run `devspace run cmd1`
    Output should be "some value".
6. Run `devspace run cmd2`
    Output should be "A different value" but is still "some value".

My devspace.yaml:
```
version: v2beta1
name: devspacetest

vars:
  VAR1:
    value: "some value"

commands:
  cmd1: |-
    echo ${VAR1}
  cmd2: |-
    devspace --var VAR1="A different value" run cmd1
```

**Local Environment:**  
- DevSpace Version: v6.0.0-alpha.7 & v6.0.0-alpha.16
- Operating System: windows

**Anything else we need to know?**  
Is this an expected change and if so how should we apply variable overrides to run commands moving forward?

/kind bug
