### ISSUE TITLE
devspace print showing args section as array

### ISSUE THREAD

**Issue by Orgil** [loft-sh/devspace#2099]
**What happened?**  
devspace print command showing container arg key as array and indentation is wrong. However deployment works ok. I'm guessing that only printing to display have problem.

**What did you expect to happen instead?**  
correctly parse container arg key.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
- name: test
  image: test/test
  args:
    - node
```
devspace print shows
```
- name: test
  image: test/test
- args:
  - node
```

**Local Environment:**  
- DevSpace Version: 5.18
- Operating System: mac
- ARCH of the OS: i386
**Kubernetes Cluster: docker for desktop mac
- Kubernetes Version: 1.24

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
@Orgil thanks for creating this issue! It works correctly for me with the `devspace.yaml`:
```yaml
version: v1beta11

deployments:
  - name: test
    helm:
      componentChart: true
      values:
        containers:
          - name: test
            image: test/test
            args:
              - node
```
DevSpace will reorder the args to the top, but that is expected and does not invalidate the yaml file.
