### ISSUE TITLE
Sync is repeated when both uploadExcludePaths and downloadExcludePaths are defined

### ISSUE THREAD

**Issue by Mins** [loft-sh/devspace#2103]
**What happened?**  
Full file synchronization is repeated when restarting devspace, even without any file changes on either side.  

**What did you expect to happen instead?**  
File synchronization does not happen if there are no file changes.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
dev:
  test-app-server:
    args: ['-f', '/dev/null']
    command: [tail]
    container: test
    labelSelector:
      project: test
    name: test-app-server
    sync:
    - uploadExcludePaths:
      - "**"
      - "!/app/"
      downloadExcludePaths:
      - "**"
      path: "./:/app"
name: test
pipelines:
  test-app-server:
    run: |
      start_dev test-app-server
version: v2beta1

```

**Local Environment:**  
- DevSpace Version: 6.0.0-alpha.19
- Operating System:mac
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider:  other
- Kubernetes Version: 1.23

**Anything else we need to know?**  
This is fixed when using `disableDownload: true`, or when using `excludePaths` without `downloadExcludePaths`

/kind bug
