### ISSUE TITLE
Cannot seem to create a DependencyConfig

### ISSUE THREAD

**Issue by withinboredom** [loft-sh/devspace#2119]
**What happened?**  

Read the docs and created a list of dependencies like:

```yaml
dependencies:
- name: api-server
  source:
    git: https://github.com/my-api-server
    branch: stable
  dev:
    sync: true
```

Got an error:

```
line 7: cannot unmarshal an array into map[string]*latest.DependencyConfig (line 7: - name: api-server)
```

Looking at the code: https://github.com/loft-sh/devspace/blob/master/pkg/devspace/config/versions/latest/schema.go#L103

It appears to want a map of strings and not an array. So I tried:

```yaml
dependencies:
  api-server: 
    name: api-server
    source:
      git: https://github.com/my-api-server
      branch: stable
    dev:
      sync: true
```

Which now fails with 

```
line 9: field source not found in type latest.DependencyConfig (line 9: source:)
```

It appears there's no definition for "source" in the schema.

**What did you expect to happen instead?**  

Dependencies to work

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: test
dependencies: 
  - name: api-server
    source:
      git: https://github.com/my-api-server
      branch: stable
    dev:
      sync: true
```

**Local Environment:**  
- DevSpace Version: 6.0.0-beta.0
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: none
- Kubernetes Version: N/A

/kind bug

**Comment by FabianKramm** [comment]
@withinboredom thanks for creating this issue! Yes you are correct seems like our documentation is wrong currently, it should look like:
```
version: v2beta1
name: test
dependencies:
  api-server: 
    git: https://github.com/my-api-server
    branch: stable
    pipeline: dev
```
