### ISSUE TITLE
devspace list ports returns nothing

### ISSUE THREAD

**Issue by tobalsgithub** [loft-sh/devspace#2133]
**What happened?**  

I'm using version `6.0.0-beta.3` of devspace. 

I have 2 ports forwarded in sync mode.
![image](https://user-images.githubusercontent.com/1554930/175725822-bc1c3202-b423-4fd4-bc50-e1a2320e3d86.png)

`devspace list ports` returns nothing
![image](https://user-images.githubusercontent.com/1554930/175735206-6690fb82-8333-493d-972f-c6d1283b636f.png)

**What did you expect to happen instead?**  
I expect to see the 2 ports that are currently forwarded.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```

-------------------

Vars:

           NAME         |                               VALUE
  ----------------------+--------------------------------------------------------------------
    DEVSPACE_TMPDIR     | /var/folders/9z/25lc8jjn6mj7c4_yj7nyj1fw0000gp/T/
    DEVSPACE_VERSION    | 6.0.0-beta.3
    DEVSPACE_USER_HOME  | <redacted>
    REDOX_SERVICES_PATH | <redacted>
    DEVSPACE_RANDOM     | BmueGp
    DEVSPACE_PROFILE    |
    DEVSPACE_CONTEXT    | <redacted>
    DEVSPACE_TIMESTAMP  | 1656112748
    devspace.context    | <redacted>
    devspace.namespace  | <redacted>
    DEVSPACE_NAMESPACE  | <redacted>
    DEVSPACE_NAME       | configurations


-------------------

Loaded path: /Users/tc/code/redox-services/services/configurations/devspace.yaml

-------------------

Dependency Tree:

-------------------

version: v2beta1
name: configurations
pipelines:
    deploy:
        run: |-
            run_dependencies --all
            create_deployments --all
    dev:
        run: |-
            run_dependencies --all
            create_deployments --all
            start_dev --all
deployments:
    app:
        kubectl:
            manifests:
                - ./redoxlocal/configmap.yaml
                - ./redoxlocal/migrate.yaml
                - ./redoxlocal/manifest.yaml
dev:
    execution:
        labelSelector:
            service: configurations
            service-target-name: configurations-execution
        command:
            - bash
            - -c
            - npx redox-start --ignoreVault -- src/execution.ts
        sync:
            - path: ./
              excludeFile: .gitignore
              startContainer: true
              onUpload:
                restartContainer: true
                exec:
                    - name: npm-install
                      command: npm ci
                      onChange:
                        - ./package-lock.json
              disableDownload: true
        ports:
            - port: 9230:9229
    web:
        labelSelector:
            service: configurations
            service-target-name: configurations
        command:
            - bash
            - -c
            - npm run debug
        sync:
            - path: ./
              excludeFile: .gitignore
              startContainer: true
              onUpload:
                restartContainer: true
                exec:
                    - name: npm-install
                      command: npm ci
                      onChange:
                        - ./package-lock.json
              disableDownload: true
        ports:
            - port: 9229:9229
```

**Local Environment:**  Mac OS Monterey
- DevSpace Version: `6.0.0-beta.3`
- Operating System: mac
**Kubernetes Cluster:**  
- Cloud Provider: aws 
- Kubernetes Version: `1.22`

/kind bug
