### ISSUE TITLE
imports does not import profiles

### ISSUE THREAD

**Issue by tobalsgithub** [loft-sh/devspace#2134]
**What happened?**  
I'm unsure if this is a bug or a feature request. 

I tried to use the new `imports` feature in v6 to import a profile. I want to be able to standardize some profiles across many different applications, so importing them seemed like the best way to do this ( can't use expressions cause expressions don't work in the profiles section as I understand). 

However, when doing this, the profile does not seem to be imported. 

**What did you expect to happen instead?**  
I don't see anyting in the documentation that suggests profiles will not be imported. So either I would expect the docs to make it clear what types of things can be imported and which can't, or I would expect profile imports to work the same way other sections work. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Here's the devspace.yaml that I want the profile imported into. Note the `imports` statement towards the top:
```yaml
version: v2beta1
name: email
imports:
  - path: ../../devspace/default-pipelines.yaml
deployments:
  email:
    kubectl:
      manifests:
        - ./redoxlocal/configmap.yaml
        - ./redoxlocal/manifest.yaml
dev:
  email:
    labelSelector:
      service: email
      service-target-name: email-app
      ksync: app
    command:
      - bash
      - -c
      - npm run debug
    args: []
    ports:
      - port: 9229:9229
    sync:
      - $(cat ../../devspace/default-terminal-sync.yaml)
```

And here's the file that has the "shared" profile and pipelines:
```yaml
version: v2beta1
name: default-pipelines

imports:
- path: ./common.yaml

pipelines:
  dev:
    run: |-
      run_dependencies --all
      create_deployments --all
      start_dev --all
  deploy:
    run: |-
      run_dependencies --all
      create_deployments --all

profiles:
- name: logs
  patches:
    - op: replace
      path: dev.*.logs
      value:
        enabled: true
        lastLines: 200
```

When I run `devspace dev -p logs` I get the following:

> fatal Couldn't find profile 'logs'

**Local Environment:**  MacOS Monterey
- DevSpace Version: `devspace version 6.0.0-beta.3`
- Operating System:  mac
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
- Cloud Provider: aws 
- Kubernetes Version: 1.22

**Anything else we need to know?**  

/kind bug
