### ISSUE TITLE
release name cannot be set using Environment Variable with devspace manifest v2beta1

### ISSUE THREAD

**Issue by drpdishant** [loft-sh/devspace#2150]
**What happened?**  
With version 6 there's no way to define the release name dynamically when deploying with devspace.

**What did you expect to happen instead?**  
Previously with version 5 and devspace manifest version v1beta11 it was possible to define the deployment name i.e the helm release name with variables as it was passed as the value of name key:

```yaml
version: v1beta11
deployments:
  - name: ${SERVICE_NAME}
    helm:
      componentChart: true
```
While with manifest version v2beta1

I cannot define it like

```yaml
version: v2beta1
deployments:
 ${SERVICE_NAME}:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
```

The latter will simply fail.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Here's my template file that I am using to deploy services on kubernetes.

```yaml
version: v2beta1
deployments:
  ${PROJECT_SLUG}:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
        - image: ${CI_REGISTRY_IMAGE}@${IMAGE_DIGEST}
        pullSecrets:
        - regcred
        service:
          ports:
          - port: 80
            containerPort: ${CONT_PORT}
        ingress:
          tls: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/proxy-body-size: 100m
          rules:
          - host: ${PROJECT_SLUG}.${DEV_BASE_DOMAIN}
```

**Local Environment:**  
- DevSpace Version: devspace version 6.0.0-beta.0
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: v1.22.5

**Anything else we need to know?**  

If there's another way to define release name dynamically, please document it, we are using devspace.yaml file as template and setting deployment values in CI to define the target environment configuration. Inability to define release name as env has made us add sed exclusively to set the release name by defining __SERVICE_NAME__ as key and running `sed -i "s%__SERVICE_NAME__%$SERVICE_NAME%g" devspace.yml` to set the value.

/kind bug

**Comment by FabianKramm** [comment]
@drpdishant thanks for creating this issue! Yes you are correct thats currently not doable, however we can add a new option like this:
```yaml
version: v2beta1
deployments:
  my-deployment:
    helm:
      releaseName: ${PROJECT_SLUG}
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
        - image: ${CI_REGISTRY_IMAGE}@${IMAGE_DIGEST}
        pullSecrets:
        - regcred
        service:
          ports:
          - port: 80
            containerPort: ${CONT_PORT}
        ingress:
          tls: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/proxy-body-size: 100m
          rules:
          - host: ${PROJECT_SLUG}.${DEV_BASE_DOMAIN}

```

Which would allow you to set a release name via an environment variable.
