### ISSUE TITLE
Optionally, keep helm annotations on ReplicaSets

### ISSUE THREAD

**Issue by emoreth** [loft-sh/devspace#2181]
**Is your feature request related to a problem?**
It is not a bug,  but somewhat like a problem. When devspace replaces a pod, helm annotations are not kept:

```
annotations:
  meta.helm.sh/release-name: app-release-name
  meta.helm.sh/release-namespace: app-deploy-namespace-name
labels:
  app.kubernetes.io/managed-by: Helm
```

Which causes those pods to be left behind when one does `helm delete app-release-name`.

**Which solution do you suggest?**
Add an option `keep_helm_annotations: true|false` defaulting to false to keep current behaviour.

**Which alternative solutions exist?**

My current workaround is a custom command to proper cleanup resources:

```
commands:
 - name: clean-release
    command: |
      helm delete ${RELEASE_NAME}
      devspace run clean
    description: Deletes the helm release and all standalone pods created by DevSpace
```

**Additional context**

/kind feature
