### ISSUE TITLE
Kaniko build displaying the same output log

### ISSUE THREAD

**Issue by alexissellier** [loft-sh/devspace#2207]
**What happened?**  
When using kaniko to build two different images, the build never seems to end and the output logs are the same for both (displaying the log of the first image)

**What did you expect to happen instead?**  
Build finishes successfully and I have access to the correct log

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Run devspace build with the following devpsace.yaml file

My devspace.yaml:

```
version: v2beta1
name: devenv
images:
  web:
    image: distribution.domain/test/web:${DEVSPACE_GIT_COMMIT}
    dockerfile: dev.Dockerfile
    target: web-dev
    buildArgs:
       PHP_IMAGE_BASE: stable
    kaniko:
      pullSecret: github-registry
 assets:
    image: distribution.domain/test/assets:${DEVSPACE_GIT_COMMIT}
    dockerfile: dev.Dockerfile
    target: assets-dev
    kaniko:
      pullSecret: github-registry

```

**Local Environment:**  
- DevSpace Version: 6.0.0-beta.8
- Operating System: Linux
- ARCH of the OS: amd64
**Kubernetes Cluster:**  
- Cloud Provider: google 
- Kubernetes Version: 1.24.1

**Anything else we need to know?**  

/kind bug
