### ISSUE TITLE
pipeline flags cannot be used if variable with input is used

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/devspace#2237]
**What happened?**  
Pipeline flags are not parsed correctly if variables with input are used in the config, e.g.:
```
version: v2beta1
name: flags
vars:
  MY_VAR:
    default: test

pipelines:
  dev:
    flags:
    - name: test
      type: bool
    run: |-
      echo "$(get_flag test)"
```

Running `devspace dev --test` will result in the error `flag --test not found`
