### ISSUE TITLE
Commands fail to render

### ISSUE THREAD

**Issue by MathiasVandePol** [loft-sh/devspace#2239]
![image](https://user-images.githubusercontent.com/606681/186382442-da3e4991-a6d2-4466-a615-7ddbc81e998b.png)

**What happened?**  
Command will not show in the devspace ui

**What did you expect to happen instead?**  
A list of command which I can execute.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
....

commands:
  "db-setup-testdb-testsegmentdb":
    command: "bash scripts/setup-db.sh localhost ${POSTGRES_USER} ${POSTGRES_PASSWORD}"
  "db-seed-hermes":
    command: "bash scripts/seed-hermes.sh localhost ${POSTGRES_USER} ${POSTGRES_PASSWORD}"
  "db-seed-walter":
    command: "bash scripts/seed-walter.sh localhost ${POSTGRES_USER} ${POSTGRES_PASSWORD}"
  "db-seed-sqlschema":
    command: "bash scripts/seed-sqlschema.sh localhost ${POSTGRES_USER} ${POSTGRES_PASSWORD}"

```

**Local Environment:**  
- DevSpace Version: 6.0.0
- Operating System:  mac
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider:  other (local)
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug
