### ISSUE TITLE
Functions that share the same name as a pipeline give errors

### ISSUE THREAD

**Issue by ethankhall** [loft-sh/devspace#2247]
**What happened?**  

I have a function and pipeline called `test`. When running `devspace run-pipeline test` the output is

```
devspace run-pipeline test
info Using namespace 'ethan-hall'
info Using kube context 'loft_ethan-hall_portland'
fatal exit status 1
```

**What did you expect to happen instead?**  

To run the `test` function or a useful error message.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: foo
functions:
  test: |-
    env
pipelines:
  test: |-
    test
```

**Local Environment:**  
- DevSpace Version: 6.0.0
- Operating System: mac
- ARCH of the OS: ARM64

/kind bug
