### ISSUE TITLE
Running commands fails if question variable is set and used

### ISSUE THREAD

**Issue by MathiasVandePol** [loft-sh/devspace#2266]
![image](https://user-images.githubusercontent.com/606681/187161142-6d55abef-f350-40fc-b313-d57e85e4a964.png)

I have a var set 
```
  ANIMAL:
    question: Which type of animal are you
    options:
      - "cat"
      - "dog"
 
```
and a profile (this is optional, also fails without)

```
profiles:

  - name: no-humans
    activation:
      - vars:
          ANIMAL:"cat"
```

When running a command ex: `devspace run 'somecommand'` it will try to use the question variable which fails as commands are not being run in a terminal 

**What happened?**  

Commands stop execution with `Cannot ask question`

**What did you expect to happen instead?**  

Ideally, there should be an option to ignore variables when a `command` is executed.
For example. I use commands to seed some data in the database for which only db connection string vars are required. The rest I should not need.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1

vars:
  ANIMAL:
    question: Which type of animal are you
    options:
      - "cat"
      - "dog"

commands:
  "test-command":
      command: "echo 'hi'"

profiles:
  - name: no-humans
    activation:
      - vars:
          ANIMAL:"cat"
```

**Local Environment:**  
- DevSpace Version: 6.0.1
- Operating System:  mac
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**  

/kind bug
