### ISSUE TITLE
datatype of targetAverageUtilization for Horizontal Pod Autoscaling,  got "string", expected "integer"

### ISSUE THREAD

**Issue by Rishang** [loft-sh/devspace#2268]
For Horizontal Pod Autoscaling,

While using autoscaling based on `targetAverageUtilization`, i was facing this issue in DevSpace version : 6.0.1

Input:
```yml
  replicas: 1
  autoScaling:
    horizontal:  
      maxReplicas: 3
      averageRelativeMemory: 40
```
Error while applying chart:
```
ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource.targetAverageUtilization): invalid type for io.k8s.api.autoscaling.v2beta1.ResourceMetricSource.targetAverageUtilization: got "string", expected "integer"
```

References:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale

targetAverageUtilization requires integer, but string was been given, so have provided fixes for that. [here](https://github.com/loft-sh/component-chart/pull/81)
