### ISSUE TITLE
[Devspace6] Using variables mixed in between imports/functions/dependencies/etc.

### ISSUE THREAD

**Issue by karbowiak** [loft-sh/devspace#2271]
Using Devspace 5 the following was achievable:

```
version: v1beta11

vars:
  - name: PROJECT_TYPE
    default: devspace
    options:
      - "devspace_type_one"
      - "devspace_type_two"

images:
  web:
    image: web.${PROJECT_TYPE}.Dockerfile
    ....
```

With Devspace6 i was trying to split things out a bit more using imports, by doing something similar using variables.

```
version: v2beta1
name: example-please-change-to-actual-name

vars:
  PROJECT_TYPE:
    question: What project type is this?
    default: project_type_one
    options:
      - "project_type_one"
      - "project_type_two"

imports:
  - git: git-repository.git
    tag: master
    subPath: devspace-configs/${PROJECT_TYPE}
```

where the subpath contains a `devspace.yaml` and a `commands.yaml` that the `devspace.yaml` imports using local path imports.

But sadly, the following error is being spit out when i try `devspace print`

`fatal read import config: open ~/.devspace/dependencies/git-repository-git-tag-master/devspace-configs/${PROJECT_TYPE}/devspace.yaml: no such file or directory`

Having the ability to utilize the vars throughout the devspace.yaml (maybe even in the files that are imported) would be awesome in terms of being able to make things dynamic :)

/kind feature
