### ISSUE TITLE
devspace with own helm repo fails to start

### ISSUE THREAD

**Issue by adapasuresh** [loft-sh/devspace#2280]
**What happened?**  
Upgraded the devspace, its says 
devspace --version
devspace version 6.0.1

**What did you expect to happen instead?**  
deploy and run the pods in my namespace

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: java-app-dtom

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      create_deployments --all     # 2. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 3. Start dev mode "app" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      build_images --all -t $(git describe --always)    # 2. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 3. Deploy Helm charts and manifests specfied as "deployments"

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: inunwpcodb432.abcdefg.com:9084/plural_nonprod_appimages:pine-java-app
    dockerfile: ./Dockerfile

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: ./pine-java-helm
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles:
        - "pine-java-helm/values.yaml"
      #values:
        #someChartValue: "values.yaml"

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    imageSelector: inunwpcodb432.abcdefg.com:9084/plural_nonprod_appimages:pine-java-app
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    #devImage: ghcr.io/loft-sh/devspace-containers/java-maven:3-openjdk-17-slim
    devImage: inunwpcodb432.abcdefg.com:9084/plural_nonprod_appimages:pine-java-app
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "8080"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:8080

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  start:
    command: |
      devspace enter -- bash -c '
        # Remove old .jar files
        rm -f target/*.jar

        # Build jar file
        MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        mvn package -T 1C -U -Dmaven.test.skip=true

        java -jar target/*.jar'

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)

...
```

**Local Environment:**  
- DevSpace Version: 6.0.1
- Operating System:  mac
- ARCH of the OS: apple M1
**Kubernetes Cluster:**  
- Cloud Provider:  aws 
- Kubernetes Version: [use `kubectl version`]
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  

sureshadapa@localhost pine-java-app % devspace dev
info Using namespace 'abcedfg-demo'
info Using kube context 'arn:aws:eks:ap-south-1:22222222222222:cluster/xxxxxxEKSCL147'
deploy:app Deploying chart ./pine-java-helm (app) with helm...
deploy:app Deployed helm chart (Release revision: 5)
deploy:app Successfully deployed app with helm
start_dev: replace pod: couldn't find a matching deployment, statefulset or replica set
fatal exit status 1

/kind bug

**Comment by carlmontanari** [comment]
👋 hey there -- it looks like the chart gets deployed successfully but we can't find a pod to replace. Can you share a bit of whats going on in your cluster in that `abcedfg-demo` namespace? Probably would be good to see the yaml dump from the pod you are trying to replace.

**Comment by adapasuresh** [comment]
I guess, I need to correct my private nexus docker uri for the container->image. Wondering if you can share sample devspace.yaml with private repo , user and pwd settings

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adapasuresh** [comment]
I am trying to enable 11 scrum teams to use devspace , and perform end-end deployed , later plan to use similar for entire org

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianKramm** [comment]
Hey @adapasuresh ! So in general it makes sense to use variables to define the repository you want to push to and to use pull secrets:
```
version: v2beta1
name: java-app-dtom

vars:
  MY_REPO: inunwpcodb432.abcdefg.com:9084/plural_nonprod_appimages
  # Ask the user to enter his own repo
  # MY_REPO:
  #   default: inunwpcodb432.abcdefg.com:9084/plural_nonprod_appimages
  REGISTRY_USER: my-user
  REGISTRY_PASSWORD: $( cat password.txt )

pullSecrets:
  my-repo:
    registry: inunwpcodb432.abcdefg.com:9084
    username: ${REGISTRY_USER}
    password: ${REGISTRY_PASSWORD}

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app:
    image: ${MY_REPO}
    dockerfile: ./Dockerfile

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: ./pine-java-helm
      #valuesFiles:
      #  - "pine-java-helm/values.yaml"
      values:
        image: ${MY_REPO}

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Search for the container that runs this image
    imageSelector:${MY_REPO}
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "8080"

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  start:
    command: |
      devspace enter -- bash -c '
        # Remove old .jar files
        rm -f target/*.jar

        # Build jar file
        MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        mvn package -T 1C -U -Dmaven.test.skip=true

        java -jar target/*.jar'
```
