### ISSUE TITLE
The default setting for deployment.updateImageTags seems wrong

### ISSUE THREAD

**Issue by andrstor** [loft-sh/devspace#2285]
**What happened?**  
The documentation for [updateImageTags ](https://devspace.sh/docs/configuration/deployments/#deployments-updateImageTags) says that the default value is ``false``, but it seems that if you dont add the setting and explicitly sets it to ``false``, the behaviour defaults to ``true``

**What did you expect to happen instead?**  
``updateImageTags`` should behave as if set to false if not set in ``devspace.yaml``

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- Create a ``devspace.yaml`` setup with both deployments and images.
- Specify image specifically for the deployment. For instance in ``values.yaml`` for helm.
- Run ``devspace build`` to build images.
- Run ``devspace deploy`` to deploy to kubernetes.

In my understanding, the deployment should now use the specific image set for the deployment, not overwrite with the latest built ``devspace build`` images

My devspace.yaml:
```
version: v2beta1 
name: hn-configuration

pipelines:
  build:
    build_images --all
  deploy: |-              
    create_deployments --all             

deployments:
  configuration: 
    # updateImageTags: false   
    namespace: dev     
    helm:                                   
      chart: 
        name: charts
      displayOutput: true
      upgradeArgs: 
        - '--render-subchart-notes'
        - '--dependency-update'
      valuesFiles:
        - charts/values.common.yaml
        - charts/values.dev.yaml

images:
  api: 
    image: ...
    dockerfile: ...
```

**Local Environment:**  
- DevSpace Version: 6.0.1
- Operating System: windows 
- ARCH of the OS: ARM64 
**Kubernetes Cluster:**  
- Cloud Provider:  KIND
- Kubernetes Version: [use `kubectl version`]
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```
**Anything else we need to know?**  

/kind bug
