### ISSUE TITLE
AutoReload functionality removed before a replacement is available

### ISSUE THREAD

**Issue by ComaVN** [loft-sh/devspace#2322]
**What happened?**
I upgraded devspace, and tried to run my existing devspace projects in version 6.1.1

Devspace tells me:

```
error Auto reload is not supported anymore in DevSpace version 6 and has no effect. Please update your config and use rerunning jobs instead
```

In the 6.0.0 release notes, it says: `This functionality was removed from DevSpace and will be replaced in future by automatically reloading pipelines`

I could not find any further information about reloading pipelines, so I'm not sure if these are implemented yet, and if so, how to use them to replace the old `autoReload` functionality

**What did you expect to happen instead?**
I expect breaking changes to have a working replacement, and some documentation on how to achieve the same functionality using the new system

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v1beta11
images:
  server:
(...)
deployments:
  - name: to-devacct-cluster
    kubectl:
      replaceImageTags: true
      kustomize: true
      manifests:
        - manifests/overlays/development/devspace
      cmdPath: custom-kubectl-for-devspace
dev:
  ports:
    - imageSelector: image(server):tag(server)
      forward:
        - port: 8081
          remotePort: 8080
        - port: 2345
  sync:
    - imageSelector: image(server):tag(server)
      localSubPath: container/server
      containerPath: /app
      initialSyncCompareBy: size
      onUpload:
        restartContainer: true
        execRemote:
          command: sh
          args:
            - -c
            - "killall __debug_bin || true"
  autoReload:
    images:
      - server
    paths:
      - devspace.yaml
      - manifests/base/*
      - manifests/overlays/development/devspace/*
      - manifests/overlays/development/devspace/secrets/*
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: linux
* ARCH of the OS: AMD64

**Kubernetes Cluster:**

* Cloud Provider: other
* Kubernetes Version: Client v1.25.1, Server v1.24.3

**Anything else we need to know?**

/kind bug
