### ISSUE TITLE
"Inherit" imported sections from devspace.yaml to create reusable defaults that can be overriden locally

### ISSUE THREAD

**Issue by andrstor** [loft-sh/devspace#2337]
**Is your feature request related to a problem?**  
The problem we are trying to solve is how to scale devpace.yaml to a large number of repositories without having to repeat yourself over and over.

We have a set of very similar repos and applications (50+) were we are working on implementing devspace. To ease the implementation we are using reusible parts in devspace.yaml (e.g. imports) whenever possible. Still, we have to type out the dev: section of each devspace.yaml, even though they only differs in a few places (typically labelselector, devimage and args). Could this be "templated"/centralized in som way? 

**Which solution do you suggest?**  
_Proposed solution from loft-users slack thread:_

```yaml
dev:
  my-parent:
    defaultDisabled: true
    sync: 
      ...
    ports:
      ...
  my-dev:
    parent: my-parent
    imageSelector: ...
```
Then ``my-dev`` would reuse the ``my-parent`` settings and override the imageSelector only. This would allow you to put ``my-parent`` in an import and then just override the settings you want. 

This should be added for ``images`` , ``dev`` , ``pullSecrets`` and ``deployments``

**Which alternative solutions exist?**  
None as far as I'm aware.

**Additional context**  

/kind feature
