### ISSUE TITLE
is_dependency does not return enything

### ISSUE THREAD

**Issue by GaRiY** [loft-sh/devspace#2342]
**What happened?**  
is_dependency did not return enything.

**What did you expect to happen instead?**  
In DevSpace docs devspace.yaml/functions section it says that:
> is_dependency  (returns: bool)
> Returns true if the pipeline currently being executed is run because the project is a dependency of another project

**How can we reproduce the bug?** (as minimally and precisely as possible)  
My 2 devspace files are enough.

My dependency devspace.yaml:
``` yaml
version: v2beta1
name: dep

pipelines:
  my-pipe: |-
    echo $(is_dependency)
```

My main devspace.yaml:
``` yaml
version: v2beta1
name: test

pipelines:
  test:
    run_dependency_pipelines dep-1

dependencies:
  dep-1:
    path: ./dependency
    pipeline: my-pipe
```

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: linux
- ARCH of the OS: AMD64

**Kubernetes Cluster:**  
- Cloud Provider: other (k8s in docker (kind))
- Kubernetes Version: 
  - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
  - Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**  
file structure:
``` bash
.
├── dependency
│   └── devspace.yaml      (dependency)
└── devspace.yaml          (main)
```

/kind bug
