### ISSUE TITLE
After deployment using devspace dev, any change in deployment name causes ErrImagePull.

### ISSUE THREAD

**Issue by sreepathy-tl** [loft-sh/devspace#2367]
**What happened?**  
I deployed devspace quickstart project for PHP.
After exit from `devspace dev` prompt, I edited `devspace.yaml`
Deployment name was to be changed to app3
Once changes are done, `devspace dev` fails to create container.

```
❯ devspace dev
info Using namespace 'devspace'
info Using kube context 'rancher-desktop'
deploy:app3 Deploying chart /Users/*******/.devspace/component-chart/component-chart-0.8.5.tgz (app3) with helm...
deploy:app3 Deployed helm chart (Release revision: 1)
deploy:app3 Successfully deployed app3 with helm
dev:app3 Pod was already replaced, retrying to update the configuration
dev:app3 Waiting for pod to become ready...
dev:app3 Pod app3-5b88fbf7c9-d5dks has critical status: ErrImagePull. DevSpace will continue waiting, but this operation might timeout
dev:app3 Pod app3-5b88fbf7c9-d5dks has critical status: ImagePullBackOff. DevSpace will continue waiting, but this operation might timeout
```
A deployment named app3 is created with a failing container.

Edit:
Reverting `app3` back to `app` too will fail (see that it's referencing old pod):
```
❯ devspace dev
info Using namespace 'devspace'
info Using kube context 'rancher-desktop'
deploy:app Deploying chart /Users/********/.devspace/component-chart/component-chart-0.8.5.tgz (app) with helm...
deploy:app Deployed helm chart (Release revision: 6)
deploy:app Successfully deployed app with helm
dev:app Waiting for pod to become ready...
dev:app Pod app3-5b88fbf7c9-d5dks has critical status: ImagePullBackOff. DevSpace will continue waiting, but this operation might timeout
```

**What did you expect to happen instead?**  
app3 should have been deployed successfully.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

- Follow steps for quick start php: https://www.devspace.sh/docs/getting-started/initialize-project
- After devspace dev prompt is ready, exit it
- Change `app` to `app3` on lines: 11, 22, 28, 46 in `devspace.yaml` file 
- Deploy it again using `devspace dev`
- You will get a failing app pod

My devspace.yaml:
```
version: v2beta1
name: devspace-quickstart-php

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      create_deployments --all     # 2. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app3                # 3. Start dev mode "app" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      build_images --all -t $(git describe --always)    # 2. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 3. Deploy Helm charts and manifests specfied as "deployments"

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  app3:
    image: my-image-registry.tld/username/app
    dockerfile: ./Dockerfile

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app3:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      values:
        containers:
          - image: my-image-registry.tld/username/app
        service:
          ports:
            - port: 80

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app3:
    # Search for the container that runs this image
    imageSelector: my-image-registry.tld/username/app
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/loft-sh/devspace-containers/php:8-apache
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: 7004:80
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:7004

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

# Define dependencies to other projects with a devspace.yaml
# dependencies:
#   api:
#     git: https://...  # Git-based dependencies
#     tag: v1.0.0
#   ui:
#     path: ./ui        # Path-based dependencies (for monorepos)

...
```

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: mac
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
- Cloud Provider: other - used rancher desktop
- Kubernetes Version: 
```
clientVersion:
  buildDate: "2022-08-17T18:54:23Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-25T03:45:26Z"
  compiler: gc
  gitCommit: c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e
  gitTreeState: clean
  gitVersion: v1.24.4+k3s1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
```

/kind bug
