### ISSUE TITLE
`devspace dev` fails after changes in devspace.yaml and custom helm charts - mainly due to helm errors

### ISSUE THREAD

**Issue by sreepathy-tl** [loft-sh/devspace#2368]
**What happened?**  
`devspace dev` hides the errors from helm deployment. In this specific case, my helm chart failed to install with `helm install` due to the following error:

```
❯ helm install sampleapp ./Chart -n develop
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "entry2" in namespace "develop" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "sampleapp": current value is "app"
```
But devspace failed with error:
```
11:25:00 dev:app Stopped dev app
11:25:00 start_dev: replace pod: couldn't find a matching deployment, statefulset or replica set
11:25:00 fatal exit status 1
```

**What did you expect to happen instead?**  
Actual helm error should have been reported.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Create 2 deployment charts with same names for a config map item.
Try to deploy them separately through 2 different devspace.yaml files with Chart location specified in  devspace.yaml like so:
```
deployments:
  app:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: ./Chart
```

My devspace.yaml:
```
Doesn't matter. Just ensure that you are using a local helm based deployment
...
```

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: mac
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
- Cloud Provider: other - used rancher desktop
- Kubernetes Version: 
```
clientVersion:
  buildDate: "2022-08-17T18:54:23Z"
  compiler: gc
  gitCommit: 95ee5ab382d64cfe6c28967f36b53970b8374491
  gitTreeState: clean
  gitVersion: v1.24.4
  goVersion: go1.18.5
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-08-25T03:45:26Z"
  compiler: gc
  gitCommit: c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e
  gitTreeState: clean
  gitVersion: v1.24.4+k3s1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
```

**Anything else we need to know?**  

/kind bug
