### ISSUE TITLE
`devspace dev` command is not working because url download link for `devspacehelper` cannot be found

### ISSUE THREAD

**Issue by thatGreekGuy96** [loft-sh/devspace#2395]
**What happened?**  
Trying to run the `devspace dev` command for a project I'm working on and I am getting the following error.
```
[done] √ Deployed helm chart (Release revision: 1)                        
[done] √ Successfully deployed quickstart with helm                       
[warn]   Couldn't start UI server: download ui: download ui tar ball: Couldn't find ui in github release v5.18.5 at url https://github.com/loft-sh/devspace/releases/tag/v5.18.5
[0:ports] Port-Forwarding: Waiting for containers to start...
[0:sync] Waiting for containers to start...
[0:ports] DevSpace is waiting, because Pod quickstart-56fc889d5-r6hk2 has status: ContainerCreating
[0:ports] DevSpace is waiting, because Pod quickstart-56fc889d5-r6hk2 has status: ContainerCreating
[0:sync] Starting sync...
[0:ports] Port forwarding started on 3000:3000 (user-andy-config-validation/quickstart-56fc889d5-r6hk2)
[fatal]  start sync: start sync: download devspace helper: find download URL: couldn't find devspacehelper in github release v5.18.5 at url https://github.com/loft-sh/devspace/releases/tag/v5.18.5
```

**What did you expect to happen instead?**  
Would expect the `devspace dev` command to work. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  
I was trying to run the `quickstart` example in `devspace/examples/quickstart` 

My devspace.yaml:
```yaml
version: v1beta11
vars:                                # `vars` specifies variables which may be used as ${VAR_NAME} in devspace.yaml
- name: IMAGE
  value: loftsh/javascript:latest
deployments:                         # `deployments` tells DevSpace how to deploy this project
- name: quickstart
  helm:                              # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    componentChart: true             # We are deploying the so-called Component Chart: https://devspace.sh/component-chart/docs
    values:                          # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      containers:
      - image: ${IMAGE}              # Use the value of our `${IMAGE}` variable here (see vars above)
        command: ["sleep", "infinity"]
dev:                                 # `dev` only applies when you run `devspace dev`
  ports:                             # `dev.ports` specifies all ports that should be forwarded while `devspace dev` is running
  - imageSelector: ${IMAGE}          # Select the Pod that runs our `${IMAGE}`
    forward:
    - port: 3000                     # lets you access your application via localhost:3000 on your local machine
  sync:                              # `dev.sync` configures a file sync between our Pods in k8s and your local project files
  - imageSelector: ${IMAGE}          # Select the Pod that runs our `${IMAGE}`
    excludeFile: .gitignore          # Exclude everything defined in .gitignore
  terminal:                          # `dev.terminal` tells DevSpace to open a terminal as a last step during `devspace dev`
    imageSelector: ${IMAGE}          # Select the Pod that runs our `${IMAGE}`
    command: ["./devspace_start.sh"] # With this optional `command` we can tell DevSpace to run a script when opening the terminal⏎ 
```

**Local Environment:**  
- DevSpace Version: `devspace version 5.18.5`
- Operating System: mac
- ARCH of the OS: ARM64 
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  
I dug a bit into the devspace source code and it looks as though the way this `devspacehelper` download works is that we're fetching the html body of `https://github.com/loft-sh/devspace/releases/tag/v5.18.5` and doing a regex search for the download link? The issue seems to occur because that regex search is not returning anything.
