### ISSUE TITLE
Devspace asks for credentials when using dependencies from private Git repositories

### ISSUE THREAD

**Issue by lusu007** [loft-sh/devspace#2404]
**What happened?**  
I'm using a dependency from a private Git repository in my `devspace.yaml`. Devspace asks me on every execution of `devspace dev` or `devspace purge` to provide login credentials for that private repository.

**What did you expect to happen instead?**  
Devspace should use existing Git credentials or should save the provided ones to reuse them later. According to this issue #648, it should already be the case. However, it doesn't seem to work quite right.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Add a private repository as a dependency to your `devspace.yaml`
2. Execute `devspace dev`

My devspace.yaml:
```yaml
version: v2beta1
name: api

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      build_images --all -t $(git describe --always)    # 2. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 3. Deploy Helm charts and manifests specfied as "deployments"
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      create_deployments --all     # 2. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 3. Start dev mode "app" (see "dev" section)

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  app:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: api
        repo: ...
        username: ${HELM_USERNAME}
        password: ${HELM_PASSWORD}
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles: ["dev/values.yaml"]

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  app:
    # Replace the container image with this dev-optimized image (allows to skip image building during development)
    devImage: ghcr.io/lusu007/devspace-containers/typescript:18-alpine
    imageSelector: ...
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    terminal:
      command: NPM_TOKEN=${NPM_TOKEN} ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git
    # Forward the following ports to be able access your application via localhost
    ports:
      - port: "9230:9229"
      - port: "3001:3000"
    # Open the following URLs once they return an HTTP status code other than 502 or 503
    open:
      - url: http://localhost:3001
vars:
  HELM_PASSWORD:
    password: true
  NPM_TOKEN:
    question: "Please enter your NPM token:"
    password: true

dependencies:
  other-api:
    git: ...
    branch: ...
    pipeline: dev
    namespace: other-api
```

**Local Environment:**  
- DevSpace Version: 6.1.1
- Operating System: Linux Ubuntu (WSL)
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: kind
- Kubernetes Version:  v1.25.3

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
@lusu007 thanks for creating this issue! Could you try this with the new v6.2.0-alpha.0 version, it should fallback to ssh if https doesn't work?

**Comment by lusu007** [comment]
I tried it with version `v6.2.0-alpha.0` and the `main` branch itself. The fallback does not work on my system. Devspace still tries to connect to the Git repository via `https`.

If I change the repository URL from `https `to `ssh` it works. I als found out that I have not saved a password for login via `https`.

**Comment by pratikjagrut** [comment]
@lusu007 I built the `main` branch and the [v6.2.0-alpha.0](https://github.com/loft-sh/devspace/releases/tag/v6.2.0-alpha.0) zip source code from the release page, it is working fine on my system.

devspace.yaml
```
version: v2beta1
name: test

pipelines:
  test:
    run_dependency_pipelines dep-1

dependencies:
  dep-1:
    git: https://github.com/pratikjagrut/test-private.git 
    branch: main
```
<details>
<summary>Output from <b>main branch</b> devspace bin</summary>
<pre>
➜  try devspace.test dev --debug --namespace test
12:14:39 info Using namespace 'test'
12:14:39 info Using kube context 'docker-desktop'
12:14:39 debug Use config:
version: v2beta1
name: test
pipelines:
    test:
        name: test
        run: run_dependency_pipelines dep-1
dependencies:
    dep-1:
        name: dep-1
        git: https://github.com/pratikjagrut/test-private.git
        branch: main


12:14:39 warn Error cloning repo:  Error running 'git clone https://github.com/pratikjagrut/test-private.git /Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main --branch main --depth 1': error executing 'git clone https://github.com/pratikjagrut/test-private.git /Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main --branch main --depth 1':  -> Cloning into '/Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled

12:14:39 info Switching URL from https://github.com/pratikjagrut/test-private.git to git@github.com:pratikjagrut/test-private.git and will try cloning again
12:14:42 debug Pulled https://github.com/pratikjagrut/test-private.git
12:14:42 debug Run pipeline:
name: dev
run: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all
    start_dev --all


12:14:42 run_dependencies --all
12:14:42 Marked project excluded: test
12:14:42 dep-1 run_dependencies --all
12:14:42 dep-1 ensure_pull_secrets --all
12:14:42 dep-1 build_images --all
12:14:42 dep-1 create_deployments --all
12:14:42 ensure_pull_secrets --all
12:14:42 build_images --all
12:14:42 create_deployments --all
12:14:42 start_dev --all
12:14:42 debug Wait for dev to finish
</pre>
</details>

<details>
<summary>Output from <b>v6.2.0-alpha.0 zip</b> devspace bin</summary>
<pre>
➜  try devspace-6.2.0-alpha.0 dev --debug -n test
12:33:24 info Using namespace 'test'
12:33:24 info Using kube context 'docker-desktop'
12:33:24 debug Use config:
version: v2beta1
name: test
pipelines:
    test:
        name: test
        run: run_dependency_pipelines dep-1
dependencies:
    dep-1:
        name: dep-1
        git: https://github.com/pratikjagrut/test-private.git
        branch: main


12:33:24 warn Error cloning repo:  Error running 'git clone https://github.com/pratikjagrut/test-private.git /Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main --branch main --depth 1': error executing 'git clone https://github.com/pratikjagrut/test-private.git /Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main --branch main --depth 1':  -> Cloning into '/Users/pratikjagrut/.devspace/dependencies/https-github-com-pratikjagrut-test-private-git-main'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled

12:33:24 info Switching URL from https://github.com/pratikjagrut/test-private.git to git@github.com:pratikjagrut/test-private.git and will try cloning again
12:33:27 debug Pulled https://github.com/pratikjagrut/test-private.git
12:33:27 debug Run pipeline:
name: dev
run: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all
    start_dev --all


12:33:27 run_dependencies --all
12:33:27 Marked project excluded: test
12:33:27 dep-1 run_dependencies --all
12:33:27 dep-1 ensure_pull_secrets --all
12:33:27 dep-1 build_images --all
12:33:27 dep-1 create_deployments --all
12:33:27 ensure_pull_secrets --all
12:33:27 build_images --all
12:33:27 create_deployments --all
12:33:27 start_dev --all
12:33:27 debug Wait for dev to finish
</pre>
</details>
