### ISSUE TITLE
Building in Kaniko is broken from Windows in devspace 6+

### ISSUE THREAD

**Issue by mykiep** [loft-sh/devspace#2412]
**What happened?**
Devspace 6 does not appear to be able to build linux containers in kaniko from windows machines.  It appears to be working fine from my MacBook, but when I try the same from a Windows machine it fails.  We use devspace on Windows EC2 images to build in a remote cluster via Kaniko and have been unable to move from 5.18.4 because of this issue.

**What did you expect to happen instead?**
All files should be available in the /context folder in Kaniko.

**How can we reproduce the bug?** (as minimally and precisely as possible)
I setup Rancher Desktop on my windows Deskop and my macbook.  This works fine on my macbook, but fails on my windows deskop with: "error building image: error building stage: failed to get files used from context: failed to get fileinfo for /context/test.txt: lstat /context/test.txt: no such file or directory"

My devspace.yaml:

```
version: v1beta11
images:
  app:
    image: helloworld-kaniko
    dockerfile: ./Dockerfile
    context: ./
    tags:
    - ${DEVSPACE_TIMESTAMP}
    createPullSecret: false
    build:
      kaniko:
        skipPullSecretMount: true
        snapshotMode: full
        cache: false
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --no-push
```

Dockerfile

```
FROM alpine
WORKDIR /app
COPY ["test.txt", "/app"]
CMD ["/bin/echo", "'Hello world!'"]
```

test.txt

```
Testing reading from a file
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: Windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: rancher and self provisioned cluster
* Kubernetes Version: 1.25.3 and 1.24.3

**Anything else we need to know?**
This only happens when running devspace from a windows machine.  I was able to run the debug image of kaniko and the /context folder only had the Dockerfile in it.
