### ISSUE TITLE
Custom image build command: exec: "com.docker.cli": executable file not found in %PATH%

### ISSUE THREAD

**Issue by Quasarman** [loft-sh/devspace#2440]
**What happened?**

When I try to use the custom build command for an image I get an error stating `exec: "com.docker.cli": executable file not found in %PATH%` despite my path that is printed below this error message clearly containing `C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe`. I also manually checked the environment variables on my system and it is definitely there.

When I run the custom command (see below) in the terminal everything is working as expected and the image builds normally. Also all other docker commands are working just fine. I have verified that docker desktop is running and also reinstalled it twice + the various rebooting of my machine.

**What did you expect to happen instead?**

The build custom command to succeed.

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. For me its just happening when wanting to build a image with an devspace.yaml like below shows
2. Run devspace dev
3. Custom build command will fail with `exec: "com.docker.cli": executable file not found in %PATH%`

My devspace.yaml:

```
version: v1beta11
...
images:
  bento-statistics:
    image: my/bento-statistics
    build:
      custom:
        skipImageArg: true
        command: |-
          bentoml build models/bentos/statistics --version ${runtime.images.bento-statistics.tag} --do-not-track
          docker build -t ${runtime.images.bento-statistics.image}:${runtime.images.bento-statistics.tag} . -f ${devspace.userHome}/bentoml/bentos/statistics-service/${runtime.images.bento-statistics.tag}/env/docker/Dockerfile
        onChange:
          - models/bentos/statistics/bentofile.yaml
          - models/bentos/statistics/*.py
...
```

**Local Environment:**

* DevSpace Version: 5.18.5
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: other
* Kubernetes Version:
  * Client Version: v1.25.0
  * Kustomize Version: v4.5.7
  * Server Version: v1.24.2

**Anything else we need to know?**

I am running docker desktop 4.11.1
I also verified that the `com.docker.cli.exe` exists:

```
$ where com.docker.cli
C:\Program Files\Docker\Docker\resources\bin\com.docker.cli.exe
```
