### ISSUE TITLE
v6.2.0 Replaces containers names with image tags

### ISSUE THREAD

**Issue by timo-klarshift** [loft-sh/devspace#2441]
**What happened?**

I upgraded to the latest devspace version having the new local registry feature

`create Pod asterisk-speech-0 in StatefulSet asterisk-speech failed error: Pod "asterisk-speech-0" is invalid: [spec.containers[1].name: Invalid value: "localhost:30500/asterisk-speech/app:`

**What did you expect to happen instead?**

* Deployments would continue to work
* Container name not randomly modified with a local registry name which I did not even enabled

**How can we reproduce the bug?** (as minimally and precisely as possible)

**Local Environment:**

* DevSpace Version: devspace version 6.2.0
* Operating System: linux
* ARCH of the OS: i386
  **Kubernetes Cluster:**
* Cloud Provider: k3s
* Kubernetes Version:
  clientVersion:
  buildDate: "2022-11-10T22:18:49Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: archive
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
  kustomizeVersion: v4.5.7
  serverVersion:
  buildDate: "2022-10-25T19:59:38Z"
  compiler: gc
  gitCommit: f2585c1671b31b4b34bddbb3bf4e7d69662b0821
  gitTreeState: clean
  gitVersion: v1.25.3+k3s1
  goVersion: go1.19.2
  major: "1"
  minor: "25"
  platform: linux/amd64

**Anything else we need to know?**

**Comment by timo-klarshift** [comment]
It also seems to replace other random stuff. For example I have a passwords service which uses an environment variable DB_USERNAME=`passwords`. This is also replaced by `passwords:<image_hash>` - I remember having these kind of issues with earlier versions of devspace. Why are we replacing these things without context, eg it seems like all kind of values from the YAML are replaced even out of the scope of an image name.

**Comment by lizardruss** [comment]
Hi @timo-klarshift, sorry for the regression in this functionality. Could you add your `devspace.yaml` so that I can ensure this is fixed?

Thanks for reporting the issue.

**Comment by timo-klarshift** [comment]
@lizardruss sure, there you go:

```yaml
version: v2beta1
name: devspace-issue-xyz
images:
  app:
    image: mycoolapp
    dockerfile: ./Dockerfile

deployments:
  app:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: mycoolapp
            env:
              - name: DB_USER
                value: mycoolapp
                
```

`devspace render`

```yaml
---
# Source: component-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app"
  labels:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": "app"
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/chart": "component-chart-0.8.5"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      "app.kubernetes.io/name": "devspace-app"
      "app.kubernetes.io/component": "app"
      "app.kubernetes.io/managed-by": "Helm"
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": "devspace-app"
        "app.kubernetes.io/component": "app"
        "app.kubernetes.io/managed-by": "Helm"
      annotations:
        "helm.sh/chart": "component-chart-0.8.5"
    spec:
      imagePullSecrets:
      nodeSelector:
        null
      nodeName:
        null
      affinity:
        null
      tolerations:
        null
      dnsConfig:
        null
      hostAliases:
        null
      overhead:
        null
      readinessGates:
        null
      securityContext:
        null
      topologySpreadConstraints:
        null
      terminationGracePeriodSeconds: 5
      ephemeralContainers:
        null
      containers:
        - image: "localhost:30089/mycoolapp:byrpahV"
          name: "container-0"
          command:
          args:
          env:
            - name: DB_USER
              value: localhost:30089/mycoolapp:byrpahV
          envFrom:
            null
          securityContext:
            null
          lifecycle:
            null
          livenessProbe:
            null
          readinessProbe:
            null
          startupProbe:
            null
          volumeDevices:
            null
          volumeMounts:
      initContainers:
      volumes:
  volumeClaimTemplates:
---
# Source: component-chart/templates/deployment.yaml
# Create headless service for StatefulSet
```
