### ISSUE TITLE
Local Registry: Always rebuilding images

### ISSUE THREAD

**Issue by timo-klarshift** [loft-sh/devspace#2442]
**What happened?**

* I am using the local registry feature from v6.2.0
* I noticed images are always rebuilding, even if they should not
* I noticed that in `./devspace/cache.yaml` the properties `dockerfileHash`, `contextHash` and `imageContextHash` are never created whereas they should (according to the source code)

`Rebuild image localhost:30089/username/app because it was not found in the local registry`

**What did you expect to happen instead?**

Images only rebuild when there is an actual change which would create a new image

**How can we reproduce the bug?** (as minimally and precisely as possible)

```
version: v2beta1
name: devspace-issue-xyz
images:
  app:
    image: username/app
    dockerfile: ./Dockerfile

deployments:
  app:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: username/app
        service:
          ports:
            - port: 5999
```

Then do `devspace dev` or `devspace deploy`

You see that the image is rebuild every time.

The same happens if you choose `buildKit: {}`

**Local Environment:**

* DevSpace Version: v6.2.0
* Operating System: linux
* ARCH of the OS: i386
  **Kubernetes Cluster:**
* k3s (no docker)

```
clientVersion:
  buildDate: "2022-11-10T22:18:49Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: archive
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-18T18:17:40Z"
  compiler: gc
  gitCommit: 0dc63334c0db3e7b99244427615e091909fc486e
  gitTreeState: clean
  gitVersion: v1.25.4+k3s1
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/amd64
```

**Anything else we need to know?**

I will provide a fix :)
