### ISSUE TITLE
localRegistry being used even though my cluster registries work fine

### ISSUE THREAD

**Issue by igoooor** [loft-sh/devspace#2483]
**What happened?**
I have a local cluster created with `k3d` and I used the option `--registry-create myregistry.localhost` to have its own registry which I can push from my local machine and that the cluster can use to pull container images.
Even though `docker push` works fine from my local machine, when I start my devspace project I receive this output:

```
Ensuring image pull secret for registry: myregistry.localhost:5000...
Couldn't retrieve username for registry myregistry.localhost:5000 from docker store
Couldn't retrieve password for registry myregistry.localhost:5000 from docker store
local-registry: Starting Local Image Registry
local-registry: Port forwarding to local registry started on: 30521 -> 5000
Ensuring image pull secret for registry: myregistry.localhost:5000...
Couldn't retrieve username for registry myregistry.localhost:5000 from docker store
Couldn't retrieve password for registry myregistry.localhost:5000 from docker store
Ensuring image pull secret for registry: myregistry.localhost:5000...
```

But as I said, I can `docker push` from the same machine/environment where I start my devspace project, so I don't understand why devspace says that.
Plus, if in my `devspace.yaml` file I add:

```
localRegistry:
  enabled: false
```

it will still display the `Couldn't retrieve...` message, but it will actually correctly push to that registry.

**What did you expect to happen instead?**
I expected to not see these errors, and that it does not fallback to the localRegistry

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
images:
  php:
    image: myregistry.localhost:5000/platform/php
    tags:
      - latest
    dockerfile: ../../.ops/env/base/php/docker/Dockerfile
    context: ../../.ops/env/base/php/docker/
    buildArgs:
      APP_ENV: dev
      APP_DEBUG: "true"
      BUILD_ENV: local
      POST_INSTALL_HARDENING: "false"
      USER_ID: $(id -u)
  nginx:
    image: myregistry.localhost:5000/platform/nginx
    tags:
      - latest
    dockerfile: ../../.ops/env/base/nginx/docker/Dockerfile
    context: ../../.ops/env/base/nginx/docker/
  node:
    image: myregistry.localhost:5000/platform/node
    tags:
      - latest
    dockerfile: ../../.ops/env/global/node/docker/Dockerfile
    context: ../../app/metrics
```

**Local Environment:**

* DevSpace Version: 6.2.3
* Operating System: mac m1
* ARCH of the OS: ARM64
  **Kubernetes Cluster:**
* Local: k3d
* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
```

**Anything else we need to know?**
