### ISSUE TITLE
`terminal` does not always replace container entrypoint with `sleep`

### ISSUE THREAD

**Issue by ninjaprox** [loft-sh/devspace#2485]
**What happened?**

From the [document](https://www.devspace.sh/docs/configuration/dev/connections/terminal#start-new-terminal-session), `terminal` should always (given `disableReplace: false` or by default) replace the entrypoint of the container to `sleep 100000` regardless of `dev.*.command` and `dev.*.args` configs.

However, if `dev.*.command` or `dev.*.args` is set, they will override `sleep 100000`.

**What did you expect to happen instead?**

If `terminal` is used with `disableReplace: false`, it should always replace the entrypoint of the container to `sleep 100000` as mentioned in the document.
If `disableReplace: true`, it should respect `dev.*.command` and `dev.*args` if set.

**How can we reproduce the bug?** (as minimally and precisely as possible)

`devspace.yaml`

```
version: v2beta1
name: nginx-k8s
pipelines:
  dev:
    run: |-
      start_dev app
dev:
  app:
    command:
      - /docker-entrypoint.sh
    args:
      - nginx
      - -g
      - daemon off;
    imageSelector: nginx
    sync:
      - path: ./:/app
        disableDownload: true
        startContainer: false
    terminal:
      command: /bin/bash
      disableReplace: false
      disableScreen: true
    ports:
      - port: 8080:80
```

`nginx.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```

**Local Environment:**

* DevSpace Version: 6.2.3
* Operating System: mac
* ARCH of the OS: ARM64

**Kubernetes Cluster:**

* Cloud Provider: aws
* Kubernetes Version:

```
Client Version: v1.24.1
Kustomize Version: v4.5.4
Server Version: v1.21.1
```

**Anything else we need to know?**
