### ISSUE TITLE
Error 'Chart.yaml file is missing' reported for helm dependency update when custom chart name is used within dependency

### ISSUE THREAD

**Issue by j-m-harris** [loft-sh/devspace#2488]
**What happened?**

While deploying a dependency with a custom chart name an error is reported for `helm dependency update`, though the `helm upgrade` succeeds.

```
myapp deploy:myapp error running helm dependency update:  error executing 'helm dependency update --kube-context minikube': Error: Chart.yaml file is missing
myapp deploy:myapp Deployed helm chart (Release revision: 1)
```

**What did you expect to happen instead?**

`helm dependency update` should use the same custom chart name as `helm upgrade` to avoid an error.

**How can we reproduce the bug?**

Using devspace 5 config file schema with devspace 6.2.3.

Chart name is defined in a dependency, although I don't know if that is relevant to this bug.

main devspace.yaml:

```
version: v1beta11
dependencies:
  - name: myapp
    source:
      git: git@gitlab:myapp.git
```

myapp devspace.yaml specifies a custom helm chart name:

```
version: v1beta11
deployments:
  - name: myapp
    helm:
      chart:
        name: ./chart
```

Invoking helm directly in the devspace dependency checkouts:

```
cd ~/.devspace/dependencies/git-gitlab-myapp-master
helm dependency update --kube-context minikube # fails
helm dependency update ./chart --kube-context minikube # works
```

**Local Environment:**

* DevSpace Version: 6.2.3
* Operating System: Ubuntu 22.10
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Kubernetes Version: minikube 1.28.0
